# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Ji Gang's Blog"
description:  # this means to ignore newlines until "email:"
   Ji Gang's Blog - Recording Tech and Life.

email: ji.xiaod@gmail.com
#blog logo
logo: "/assets/images/df_logo.jpg"

# blog cover
cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

name: 'jixiaod'
author: 'Ji Gang'
author_image: "/assets/images/author.jpg"

paginate:	10

url: "https://jixiaod.github.io" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@jixiaod_cn'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  - icon:	weibo
    url:	https://weibo.com/jixiaod
    desc: Follow me on Weibo
    share_url: http://service.weibo.com/share/share.php
    share_title: ?title=
    share_link: "&amp;url="

  - icon:	twitter
    url:	https://twitter.com/jixiaod_cn
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	github
    url:	https://github.com/jixiaod
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:


